# ===============================
# Database Connection Settings
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=Duxinling@2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true

# ===============================
# JPA / Hibernate Settings
# ===============================
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# Mail & JWT
# ===============================
spring.mail.host=smtp.qq.com
spring.mail.port=465
spring.mail.username=2241649635@qq.com
spring.mail.password=oogxbaoftagjeafj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
app.mail.from=${spring.mail.username}

app.jwt.secret=Q1BUMjAyX1BST0pFQ1RfSldUX1NFQ1JFVF9LRVlfMjAyNl8wM18zMF9GT1JfREVWT05MWQ==
app.jwt.expiration-ms=86400000