# ===============================
# Database Connection Settings
# ===============================
# Database name is set to booking_system. It will auto-create if not exists.
spring.datasource.url=jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&serverTimezone=UTC

# TODO: You must change the username and password to their own local MySQL credentials!
# DO NOT commit your real password to Git!
spring.datasource.username=root
spring.datasource.password=Yasuo123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================
spring.jpa.database=mysql

# Automatically create or update database tables based on Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in the console for easy debugging
spring.jpa.show-sql=true

spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# Mail (SMTP) Settings
# ===============================
spring.mail.host=smtp.qq.com
spring.mail.port=465


spring.mail.username=597918354@qq.com

spring.mail.password=lowyxxfftnxebfag

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true


app.mail.from=${spring.mail.username}

# ===============================
# JWT Settings
# ===============================
# Base64 encoded 256-bit+ secret key. Using for JWT signature. Protecting token from tampering.
app.jwt.secret=Q1BUMjAyX1BST0pFQ1RfSldUX1NFQ1JFVF9LRVlfMjAyNl8wM18zMF9GT1JfREVWT05MWQ==
# 24 hours
app.jwt.expiration-ms=86400000


# ?? Spring Boot ??????? data.sql ???????
spring.sql.init.mode=always
# ??? Hibernate ??????????????????
spring.jpa.defer-datasource-initialization=true