# ===============================
# Database Connection Settings
# ===============================
# ???? booking_system
spring.datasource.url=jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&serverTimezone=UTC

# ?????????????? MySQL ???????? 123456?
spring.datasource.username=root
spring.datasource.password=password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?????????Spring Boot 3 ???????
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SESSION SETTINGS (?????)
# ===============================
# ???? none??????????????????? session ????
spring.session.store-type=none

# ===============================
# MAIL SETTINGS (?? Notification ????)
# ===============================
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=597918354@qq.com
# ??? password ????? 16 ?? QQ ???????????
spring.mail.password=ispczywxakfobehc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=597918354@qq.com